#!/bin/sh
# build.sh — bundle the collection shell for the browser / TikTok HTML runtime.
#
# Layout of the output bundle.js:
#   1) an OUTER CommonJS registry (window.require) holding the shell modules
#      admeta/menu/router/registry/main.
#   2) each GAME as an ISOLATED closure on window.__games[<id>], with its OWN
#      private require registry, so games that share basenames (config.js,
#      game.js, ...) never collide. Each closure returns that game's exports.
#
# Games are included only if their source dir exists, so the collection grows by
# dropping in a game dir + adding it to registry.js. Re-run after any edit.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
GAMES="$HERE/.."          # miniprogram/games
SHARED="$HERE/../../shared"
BUNDLE="$HERE/bundle.js"

emit_game() {   # $1=id  $2=dir  $3..=files (basenames without .js)
  id="$1"; dir="$2"; shift 2
  # skip if dir missing
  [ -d "$dir" ] || { echo "  (skip $id — no $dir)" >&2; return; }
  echo "  window.__games['$id']=(function(){"
  echo "    var __reg={},__cache={};"
  echo "    function require(p){var n=p.replace(/^.*\\//,'');if(__cache[n])return __cache[n];var m={exports:{}};__cache[n]=m.exports;__reg[n](m,m.exports,require);__cache[n]=m.exports;return __cache[n];}"
  echo "    function def(n,f){__reg[n]=f;}"
  exports_game=""
  exports_render="null"
  for f in "$@"; do
    [ -f "$dir/$f.js" ] || continue
    echo "    def('$f.js', function(module, exports, require){"
    cat "$dir/$f.js"
    echo "    });"
    [ "$f" = "render" ] && exports_render="require('render.js')"
  done
  echo "    return { game: require('game.js'), render: $exports_render };"
  echo "  })();"
}

{
  echo "// GENERATED by shell/build.sh — do not edit."
  echo "(function(){"
  echo "  window.__games = window.__games || {};"
  # --- games (isolated) ---
  emit_game watersort "$GAMES/watersort" config logic game render
  emit_game timedodge "$SHARED"          config rng game render
  emit_game suika     "$GAMES/suika"     config logic physics game render
  # --- shell modules (outer registry) ---
  echo "  var __reg={}, __cache={};"
  echo "  window.require=function(p){var n=p.replace(/^.*\\//,'');if(__cache[n])return __cache[n];var m={exports:{}};__cache[n]=m.exports;__reg[n](m,m.exports,window.require);__cache[n]=m.exports;return __cache[n];};"
  echo "  window.__define=function(n,f){__reg[n]=f;};"
  for f in admeta menu router registry main; do
    echo "  window.__define('$f.js', function(module, exports, require){"
    cat "$HERE/$f.js"
    echo "  });"
  done
  echo "})();"
} > "$BUNDLE"
echo "wrote $BUNDLE"

# copy the shared art assets into this root so index.html can load ./assets/*
# (DevTools/zip package only files under the opened root; gitignored copy).
rm -rf "$HERE/assets"
[ -d "$GAMES/assets" ] && cp -R "$GAMES/assets" "$HERE/assets" && echo "copied assets/ -> shell/assets"
