#!/bin/sh
# build.sh — bundle the pure CommonJS modules (config/logic/game/render/main)
# into ONE browser file with a tiny inline require() registry, exactly like
# watersort/build.sh. Modules are wrapped, never edited, so the Node tests keep
# importing them directly.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
BUNDLE="$HERE/bundle.js"
{
  echo "// GENERATED by build.sh from ./*.js — do not edit."
  echo "(function(){"
  echo "  var __reg={}, __cache={};"
  echo "  window.require=function(p){var n=p.replace(/^.*\\//,'');"
  echo "    if(__cache[n])return __cache[n];"
  echo "    var m={exports:{}};__cache[n]=m.exports;"
  echo "    __reg[n](m,m.exports,window.require);__cache[n]=m.exports;return __cache[n];};"
  echo "  window.__define=function(n,f){__reg[n]=f;};"
  for f in config logic game render main; do
    echo "  window.__define('$f.js', function(module, exports, require){"
    cat "$HERE/$f.js"
    echo "  });"
  done
  echo "})();"
} > "$BUNDLE"
echo "wrote $BUNDLE"
