#!/bin/sh
# prepare.sh — assemble each platform's project root from the single-source
# canonical folders, because WeChat/Douyin DevTools package only files under the
# opened root and require() paths may not escape it.
#
# Subpackage (分包) layout produced here, per platform (wechat/ and douyin/):
#   <plat>/                 MAIN package
#     game.js game.json project.config.json adapter.js   (checked in)
#     boot/                 <- copy of ../boot   (loading screen + launcher)
#     engine/               SUBPACKAGE root (declared in game.json "subpackages")
#       game.js             (checked in) subpackage entry (MUST be game.js)
#       shared/             <- copy of ../shared  (the JS engine)
#
# The canonical sources are ../boot (main-package launcher) and ../shared (the
# engine that ships inside the subpackage). Run this before opening either
# folder in DevTools, and re-run after editing anything in boot/ or shared/.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
for target in wechat douyin; do
  rm -rf "$HERE/$target/boot" "$HERE/$target/engine/shared"
  cp -R "$HERE/boot" "$HERE/$target/boot"
  mkdir -p "$HERE/$target/engine"
  cp -R "$HERE/shared" "$HERE/$target/engine/shared"
  echo "assembled $target/: boot/ (main) + engine/shared/ (subpackage)"
done

# TikTok Minis (HTML runtime) is a real webview with a DOM but NO CommonJS
# require(). Bundle the canonical shared/*.js — used verbatim, never edited —
# into ONE self-contained file with a tiny inline CommonJS registry, so
# index.html can `window.require('main.js')`. Modules are wrapped, not modified.
BUNDLE="$HERE/tiktok/engine.bundle.js"
{
  echo "// GENERATED by prepare.sh from ../shared/*.js — do not edit. Byte-identical"
  echo "// module bodies wrapped in a minimal browser CommonJS registry."
  echo "(function(){"
  echo "  var __reg={}, __cache={};"
  echo "  window.require=function(p){var n=p.replace(/^.*\\//,'');"
  echo "    if(__cache[n])return __cache[n];"
  echo "    var m={exports:{}};__cache[n]=m.exports;"
  echo "    __reg[n](m,m.exports,window.require);__cache[n]=m.exports;return __cache[n];};"
  echo "  window.__define=function(n,f){__reg[n]=f;};"
  for f in config rng game render main; do
    echo "  window.__define('$f.js', function(module, exports, require){"
    cat "$HERE/shared/$f.js"
    echo "  });"
  done
  echo "})();"
} > "$BUNDLE"
echo "assembled tiktok/: engine.bundle.js (browser CommonJS bundle of shared/)"

echo "done. WeChat DevTools -> miniprogram/wechat; Douyin DevTools -> miniprogram/douyin;"
echo "TikTok (HTML runtime) -> miniprogram/tiktok (open index.html / zip the folder)."
